services:
  database:
    image: mariadb
    ports:
      - 8079:3306
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    env_file:
      - .env

  wordpress:
    depends_on:
      - database
    image: wordpress:php8.3
    volumes:
      - ./packages:/var/www/html/packages
      - ./vendor:/var/www/html/vendor
      - ./web:/var/www/html/web
      - ./.env:/var/www/html/.env
      - ./.htaccess:/var/www/html/.htaccess
      # Disable images' wordpress install, we'll use the composer version
      - ./web/index.php:/var/www/html/index.php
    ports:
      - 8080:80
    env_file:
      - .env
    configs:
      - source: extra.ini
        target: /usr/local/etc/php/conf.d/extra.ini

  wordpress-cli:
    depends_on:
      - database
      - wordpress
    image: wordpress:cli-php8.3
    volumes:
      - ./web:/var/www/html/web
      - ./vendor:/var/www/html/vendor
      - ./.env:/var/www/html/.env
    env_file:
      - .env

configs:
  extra.ini:
    content: |
      memory_limit = 2048M
      upload_max_filesize = 2048M
      post_max_size = 2048M
