name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]

    steps:
    - uses: actions/checkout@v5

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build
      run: |
        npm ci
        npm run build

    - name: Upload build files
      uses: actions/upload-artifact@v5
      with:
        name: production-files
        path: ./packages/theme/build

  deploy:

    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v6
      with:
        name: production-files
        path: ./build

    - name: Run git pull on remote, install dependencies and copy artifacts
      uses: kapoko/scp-action@v0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        proxy_host: ${{ secrets.SSH_PROXY_HOST }}
        proxy_port: ${{ secrets.SSH_PROXY_PORT }}
        proxy_username: ${{ secrets.SSH_PROXY_USERNAME }}
        proxy_private_key: ${{ secrets.SSH_PROXY_PRIVATE_KEY }}
        command: |
          PATH="/home/${{ secrets.SSH_USERNAME }}/bin/:$PATH"
          cd domains/klopvaart.nl/public_html && \
          git checkout main
          if ! git pull; then
            exit 1
          fi
          composer install && \ 
          composer dump-env prod && \
          wp --path=web/wp language core update && \
          wp --path=web/wp language plugin --all update && \
          wp --path=web/wp language theme --all update && \
          wp --path=web/wp rewrite flush
          wp i18n make-json packages/theme/languages web/wp-content/languages/themes --no-purge
        source: build
        target: domains/klopvaart.nl/public_html/packages/theme
